{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "openshift-application.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    #'haproxy.router.openshift.io/balance': roundrobin
    'haproxy.router.openshift.io/timeout': {{ .Values.route.timeout }}
spec:
  host: {{ .Values.route.host }}
  path: {{ .Values.route.path }}
  port:
    targetPort: http-{{ .Values.service.port }}
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
{{- end }}
